version: '3.1'

services:
  fabay_jenkins:
    container_name: fabaytech_jenkinswithdocker
    image: fabaytech/jenkinswithdocker
    ports:
      - 8080:8080
    volumes:
      - /opt/ap_data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
